version: "3.8"
services:
  app:
    build:
      context: .
      target: production
    image: voting-app:prod]
    volumes:
      - .:/app
    ports:
      - 3100:3000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - pg-dev-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: $PROD_USERNAME
      POSTGRES_DB: $PROD_DATABASE
      POSTGRES_PASSWORD: $PROD_PASSWORD

volumes:
  pg-dev-data: