version: "3.8"
services: 
  db:
    image: postgres:15
    volumes:
      - pg-dev-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: $DEV_USERNAME
      POSTGRES_DB: $DEV_DATABASE
      POSTGRES_PASSWORD: $DEV_PASSWORD
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  app:
    build:
      context: .
      target: dev
    image: pranay:latest
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
     
volumes:
  pg-dev-data:
