name: Voting Application
on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.7
        env:
          POSTGRES_USER: ${{ secrets.PG_USER }}
          POSTGRES_PASSWORD: ${{ secrets.PG_PASSWORD }}
          POSTGRES_DB: ${{ vars.PG_DATABASE }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests with Coverage
        run: npm test

      - name: Run the Application
        run: |
          npm install
          npx sequelize-cli db:drop
          npx sequelize-cli db:create
          npx sequelize-cli db:migrate
          PORT=3000 NODE_ENV=test npx ts-node src/index.ts &
          sleep 5

      - name: Run Integration Tests
        run: |
          npm install cypress cypress-json-results nyc
          npx nyc --reporter=text-summary npx cypress run
      - name: Send Success Notification
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
                -d '{"content":"**Pipeline is Passed**"}' \
                ${{ secrets.DISCORD_WEBHOOK }}

      - name: Send Failure Notification
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
                -d '{"content":"**Pipeline is Failed**"}' \
                ${{ secrets.DISCORD_WEBHOOK }}

  deploy-to-render:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Deploy to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

