name: Voting Application
on: push
env:
  PG_DATABASE: wd-todo-test
  PG_USER: postgres
  PG_PASSWORD: postgres
jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11.7
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: vote-test-db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: npm ci

      - name: Run unit tests with coverage
        id: unit-tests
        run: |
          OUTPUT=$(npm test)
          echo "::set-output name=result::$OUTPUT"
          echo "Output for unit-tests: $OUTPUT"
      
      - name: Run the app
        id: run-app
        run: |
          npm install
          npx sequelize-cli db:drop
          npx sequelize-cli db:create
          npx sequelize-cli db:migrate
          PORT=3000 NODE_ENV=test npx ts-node src/index.ts &
          sleep 5
      
      - name: Run integration tests
        id: integration-tests
        run: |
          npm install cypress cypress-json-results nyc
          OUTPUT=$(npx nyc --reporter=text-summary npx cypress run)
          echo "::set-output name=result::$OUTPUT"
          echo "output for integration-tests: $OUTPUT"

      - name: Deploy to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
        
      - name: Send Success Notification
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
                -d '{"content":"**The pipeline failed**"}' \
                ${{ secrets.DISCORD_WEBHOOK }}

      - name: Send Failure Notification
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
                -d '{"content":"**The pipeline failed**"}' \
                ${{ secrets.DISCORD_WEBHOOK }}