name: Voting Application
on: push
env:
  PG_DATABASE: wd-todo-test
  PG_USER: postgres
  PG_PASSWORD: postgres
jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11.7
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: vote-test-db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: npm ci

      - name: Run unit tests with coverage
        id: unit-tests
        run: |
          OUTPUT=$(npm test)
          echo "::set-output name=result::$OUTPUT"
          echo "$OUTPUT"
      
      - name: Run the app
        id: run-app
        run: |
          npm install
          npx sequelize-cli db:drop
          npx sequelize-cli db:create
          npx sequelize-cli db:migrate
          PORT=3000 NODE_ENV=test npx ts-node src/index.ts &
          sleep 5
      
      - name: Run integration tests
        id: integration-tests
        run: |
          npm install cypress cypress-json-results nyc
          OUTPUT=$(npx nyc --reporter=text-summary npx cypress run)
          echo "::set-output name=result::$OUTPUT"
          echo "$OUTPUT"
      
      - name: Send notification
        run: |
          UNIT_TEST_COUNT=$(grep -oP '(\d+) passing' <<< "${{ steps.unit-tests.outputs.result }}")
          UNIT_TEST_COVERAGE=$(grep -oP 'Statements   : \K\d+.\d+' <<< "${{ steps.unit-tests.outputs.result }}")
          INTEGRATION_TEST_COUNT=$(grep -oP '(\d+) passing' <<< "${{ steps.integration-tests.outputs.result }}")
          INTEGRATION_TEST_COVERAGE=$(grep -oP 'Statements   : \K\d+.\d+' <<< "${{ steps.integration-tests.outputs.result }}")
          curl -H "Content-Type: application/json" \
               -d '{"content":"Unit Tests: '$UNIT_TEST_COUNT', Unit Test Coverage: '$UNIT_TEST_COVERAGE'% , Integration Tests: '$INTEGRATION_TEST_COUNT', Integration Test Coverage: '$INTEGRATION_TEST_COVERAGE'%"}' \
               ${{ secrets.DISCORD_WEBHOOK }}